-- ตั้งเวลาเตือนใบค้างรายเดือน (SSK-143 ส่วนที่สองของ backend SSK-130)
--
-- เดิมปุ่ม Schedule Auto-Billing ในหน้า Payments เก็บค่าไว้ใน localStorage ของเบราว์เซอร์และไม่มีงานไหนรันจริง
-- ค่าที่ตั้งจึงหายเมื่อเปลี่ยนเครื่อง และแต่ละเครื่องเห็นคนละค่า ตอนนี้ย้ายมาเก็บที่ตารางนี้ แล้วให้งานฝั่ง backend
-- ส่งเตือนใบที่ยัง PENDING ทางอีเมลเดือนละครั้ง กฎของรอบอยู่ใน docs/api-contract-billing.md
-- หัวข้อ "รอบเตือนรายเดือนทำงานอย่างไร"

-- ค่าตั้งเวลามีชุดเดียวทั้งระบบ ทำแบบเดียวกับ apartment_config ใน V3 คือแถวเดียวที่ migration ใส่ไว้ให้
-- ใช้งานได้แค่ดูกับแก้ ไม่มีสร้างเพิ่มหรือลบ
--
-- day_of_month เก็บได้ถึง 31 เดือนที่สั้นกว่าให้โค้ดหนีบเป็นวันสุดท้ายของเดือนเอง
-- (แอดมินที่อยากส่งทุกสิ้นเดือนตั้ง 31 ได้เลย ไม่ต้องเปลี่ยนค่าทุกเดือน)
-- send_time เป็นเวลาไทยแบบไม่มีโซน เหมือน remind_time ของแจ้งเตือนซ่อมใน V8
CREATE TABLE billing_schedule (
    id           SMALLINT    PRIMARY KEY,
    enabled      BOOLEAN     NOT NULL DEFAULT false,
    day_of_month INTEGER     NOT NULL,
    send_time    TIME        NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT billing_schedule_single_row_ck CHECK (id = 1),
    CONSTRAINT billing_schedule_day_ck        CHECK (day_of_month BETWEEN 1 AND 31)
);

-- ปิดไว้ก่อนเสมอ ค่าเดียวกับค่าตั้งต้นของหน้าเว็บตั้งแต่ SSK-141 ถ้าเปิดไว้ตั้งแต่ต้น ระบบที่เพิ่ง deploy
-- จะส่งอีเมลหาผู้เช่าทั้งตึกเองโดยไม่มีใครตั้งใจ
INSERT INTO billing_schedule (id, enabled, day_of_month, send_time, updated_at)
VALUES (1, false, 25, '09:00', now());

-- หนึ่งแถวคือรอบเตือนของหนึ่งเดือน แถวล่าสุดคือ "รอบล่าสุด" ที่หน้าเว็บโชว์
--
-- ทำไม period ต้อง unique
-- backend บน k8s มีสอง pod (k8s/20-backend.yaml) งานตั้งเวลาจึงตื่นพร้อมกันสองตัว pod ที่ถึงรอบต้องจองเดือนนั้น
-- ด้วยการแทรกแถวนี้ให้สำเร็จก่อนส่งอะไร ตัวที่แทรกไม่ผ่านเพราะ constraint นี้คือตัวที่แพ้แล้วข้ามไป
-- ผู้เช่าจึงได้เตือนเดือนละฉบับเดียว เป็นวิธีเดียวกับ maintenance_ticket_reminder_due_uk ใน V8
-- ไม่ใช้ ShedLock เพราะแถวนี้เป็นข้อมูลที่ต้องเก็บอยู่แล้ว ไม่ต้องเพิ่ม dependency และตารางล็อกอีกชุด
--
-- period เป็น VARCHAR ไม่ใช่ CHAR เพราะ Hibernate ตรวจ schema ตอนสตาร์ต (ddl-auto: validate)
-- แล้วไม่ยอมจับ String กับคอลัมน์ bpchar
--
-- finished_at ว่างได้ แปลว่ารอบนั้นยังส่งอยู่ หรือ pod ตายกลางทาง
-- error มีค่าเมื่อทั้งรอบส่งไม่ออกเลย เช่นเมลเซิร์ฟเวอร์ล่ม (ข้อความเดียวกับที่ API ตอบ 503)
CREATE TABLE billing_schedule_run (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period        VARCHAR(7)  NOT NULL,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at   TIMESTAMPTZ,
    sent_count    INTEGER     NOT NULL DEFAULT 0,
    skipped_count INTEGER     NOT NULL DEFAULT 0,
    failed_count  INTEGER     NOT NULL DEFAULT 0,
    error         VARCHAR(500),

    CONSTRAINT billing_schedule_run_period_uk UNIQUE (period),
    CONSTRAINT billing_schedule_run_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT billing_schedule_run_counts_ck CHECK (sent_count >= 0 AND skipped_count >= 0 AND failed_count >= 0)
);
