CREATE TABLE room (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(10)   NOT NULL,
    floor       SMALLINT      NOT NULL,
    base_rent   NUMERIC(10, 2) NOT NULL,
    note        VARCHAR(500),
    CONSTRAINT room_number_uk UNIQUE (room_number),
    CONSTRAINT room_floor_ck  CHECK (floor BETWEEN 1 AND 2),
    CONSTRAINT room_rent_ck   CHECK (base_rent >= 0)
);

CREATE TABLE tenant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(200) NOT NULL,
    phone       VARCHAR(30),
    national_id VARCHAR(20),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ตอนนี้ห้องกับผู้เช่ายังไม่รู้จักกัน ตัวเชื่อมจะเป็นตาราง lease ที่เก็บวันเริ่มวันจบสัญญา
-- ซึ่งเป็นงานชิ้นถัดไป ดูหัวข้อ "ที่ยังไม่มี" ใน README ก่อนลงมือ
