-- ตาราง lease คือตัวเชื่อมห้องกับผู้เช่าที่ V1 เขียนโน้ตค้างไว้ว่าเป็นงานชิ้นถัดไป
-- โครงตารางนี้ตกลงกับฝั่งหน้าเว็บไว้แล้วใน docs/api-contract-lease.md ห้ามแก้ฝ่ายเดียว

-- ต้องมี btree_gist ก่อน ไม่งั้นเอา room_id ที่เทียบด้วย = มารวมใน exclusion constraint ไม่ได้
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE lease (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id       BIGINT       NOT NULL REFERENCES room (id),
    tenant_id     BIGINT       NOT NULL REFERENCES tenant (id),
    start_date    DATE         NOT NULL,
    end_date      DATE,
    monthly_rent  NUMERIC(10, 2) NOT NULL,
    billing_cycle VARCHAR(10)  NOT NULL,
    status        VARCHAR(10)  NOT NULL,

    CONSTRAINT lease_rent_ck   CHECK (monthly_rent >= 0),
    CONSTRAINT lease_range_ck  CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT lease_cycle_ck  CHECK (billing_cycle IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT lease_status_ck CHECK (status IN ('ACTIVE', 'ENDED')),

    -- ตัวกันปล่อยเช่าซ้อนของจริงอยู่ตรงนี้ที่เดียว การเช็คในโค้ดเป็นแค่การทำให้ข้อความ
    -- ที่ผู้ใช้เห็นอ่านรู้เรื่อง กันสองคำขอที่เข้ามาพร้อมกันไม่ได้
    --
    -- ช่วงวันที่เป็นแบบปิดสองด้าน '[]' แปลว่าสัญญาเก่าจบวันที่ 31 ส.ค. กับสัญญาใหม่
    -- เริ่มวันที่ 31 ส.ค. ถือว่าทับกัน กฎเดียวกับ frontend/src/domain/lease.ts
    -- ถ้าจะเปลี่ยนเป็น '[)' ต้องเปลี่ยนพร้อมกันทั้งสองที่
    --
    -- WHERE (status = 'ACTIVE') ทำให้สัญญาที่ปิดไปแล้วไม่กันห้องอีก ซึ่ง US-06-S1 ต้องการ
    CONSTRAINT lease_no_overlap EXCLUDE USING gist (
        room_id WITH =,
        daterange(start_date, end_date, '[]') WITH &&
    ) WHERE (status = 'ACTIVE')
);

-- หน้าผังห้องถามว่า "ห้องนี้มีสัญญา active อยู่ไหม" ทุกครั้งที่โหลด
CREATE INDEX lease_room_status_ix ON lease (room_id, status);
