-- ตาราง lease คือตัวเชื่อมห้องกับผู้เช่าที่ V1 เขียนโน้ตค้างไว้ว่าเป็นงานชิ้นถัดไป
-- โครงตารางนี้ตกลงกับฝั่งหน้าเว็บไว้แล้วใน docs/api-contract-lease.md ห้ามแก้ฝ่ายเดียว

-- ต้องมี btree_gist ก่อน ไม่งั้นเอา room_id ที่เทียบด้วย = มารวมใน exclusion constraint ไม่ได้
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE lease (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id       BIGINT       NOT NULL REFERENCES room (id),
    tenant_id     BIGINT       NOT NULL REFERENCES tenant (id),
    start_date    DATE         NOT NULL,
    end_date      DATE,
    monthly_rent  NUMERIC(10, 2) NOT NULL,
    billing_cycle VARCHAR(10)  NOT NULL,
    status        VARCHAR(10)  NOT NULL,

    -- เงินมัดจำกับอัตราค่าสาธารณูปโภคเก็บเป็นค่าของสัญญาใบนี้เอง ไม่ได้อ้างอิงไปที่
    -- ตาราง apartment_config ทั้งที่ค่าตั้งต้นมาจากที่นั่น
    --
    -- ที่ต้องคัดลอกมาเก็บเพราะ apartment_config มีแถวเดียวทั้งตึกและถูกเขียนทับทุกครั้ง
    -- ที่แอดมินแก้อัตรา ไม่มีประวัติเก็บไว้เลย ถ้าสัญญาอ้างอิงกลับไปที่ตารางนั้น
    -- วันที่แอดมินขึ้นค่าไฟ สัญญาเก่าทุกใบจะเปลี่ยนเงื่อนไขย้อนหลังตามไปด้วย
    -- ซึ่งผิดทั้งทางบัญชีและทางกฎหมาย เพราะผู้เช่าเซ็นยอมรับอัตราชุดเดิมไว้
    --
    -- ดีไซน์จอ Create Contract เขียนกำกับเรื่องนี้ไว้ตรง ๆ ว่า
    -- "Rates default from Apartment Config and are locked into this contract once saved"
    security_deposit       NUMERIC(10, 2) NOT NULL,
    electric_rate_per_unit NUMERIC(10, 2) NOT NULL,
    water_rate_per_unit    NUMERIC(10, 2) NOT NULL,
    common_area_fee        NUMERIC(10, 2) NOT NULL,
    internet_fee           NUMERIC(10, 2) NOT NULL,

    CONSTRAINT lease_rent_ck   CHECK (monthly_rent >= 0),

    -- ศูนย์ใช้ได้ หอบางที่ไม่คิดค่าส่วนกลางหรือค่าอินเทอร์เน็ต และบางสัญญาไม่เก็บมัดจำ
    -- กฎเดียวกับ validateApartmentConfig ใน frontend/src/domain/apartmentConfig.ts
    CONSTRAINT lease_deposit_ck CHECK (security_deposit >= 0),
    CONSTRAINT lease_rates_ck   CHECK (electric_rate_per_unit >= 0
                                   AND water_rate_per_unit >= 0
                                   AND common_area_fee >= 0
                                   AND internet_fee >= 0),
    CONSTRAINT lease_range_ck  CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT lease_cycle_ck  CHECK (billing_cycle IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT lease_status_ck CHECK (status IN ('ACTIVE', 'ENDED')),

    -- ตัวกันปล่อยเช่าซ้อนของจริงอยู่ตรงนี้ที่เดียว การเช็คในโค้ดเป็นแค่การทำให้ข้อความ
    -- ที่ผู้ใช้เห็นอ่านรู้เรื่อง กันสองคำขอที่เข้ามาพร้อมกันไม่ได้
    --
    -- ช่วงวันที่เป็นแบบปิดสองด้าน '[]' แปลว่าสัญญาเก่าจบวันที่ 31 ส.ค. กับสัญญาใหม่
    -- เริ่มวันที่ 31 ส.ค. ถือว่าทับกัน กฎเดียวกับ frontend/src/domain/lease.ts
    -- ถ้าจะเปลี่ยนเป็น '[)' ต้องเปลี่ยนพร้อมกันทั้งสองที่
    --
    -- WHERE (status = 'ACTIVE') ทำให้สัญญาที่ปิดไปแล้วไม่กันห้องอีก ซึ่ง US-06-S1 ต้องการ
    CONSTRAINT lease_no_overlap EXCLUDE USING gist (
        room_id WITH =,
        daterange(start_date, end_date, '[]') WITH &&
    ) WHERE (status = 'ACTIVE')
);

-- หน้าผังห้องถามว่า "ห้องนี้มีสัญญา active อยู่ไหม" ทุกครั้งที่โหลด
CREATE INDEX lease_room_status_ix ON lease (room_id, status);
