-- ผู้ใช้ฝั่งแอดมินสำหรับ US-01 (เข้าสู่ระบบ) และ US-02 (ออกจากระบบ) ตั๋ว SSK-28
--
-- เลข V7 เพราะ V6 ถูกจองไว้ให้ฟิลด์เพิ่มของผู้เช่า (US-03) ที่ทำอยู่อีกสาขาหนึ่ง
-- ส่วนตารางใบแจ้งซ่อมของ CR-05 เลื่อนไปเป็น V8 แล้ว แก้ไว้ใน README และ
-- docs/frontend-workplan.md ให้ตรงกันแล้วเหมือนกัน
--
-- เก็บเฉพาะ hash ไม่เก็บรหัสผ่านจริง คอลัมน์ยาว 100 พอสำหรับ BCrypt ที่ออกมา 60 ตัวอักษร
-- และเผื่อไว้ให้ขึ้นเป็น argon2 หรือ scrypt ทีหลังได้โดยไม่ต้อง migrate คอลัมน์อีกรอบ
--
-- ไม่มี INSERT แถวแรกในไฟล์นี้โดยตั้งใจ รหัสผ่าน (ถึงจะ hash แล้ว) ไม่ควรอยู่ใน migration
-- เพราะ migration ถูกคอมมิตลง repo และรันเหมือนกันทุก environment แปลว่ารหัสของ
-- production จะเท่ากับรหัสที่ทุกคนที่ clone repo ได้อ่านไปแล้ว แอดมินคนแรกจึงถูกสร้าง
-- ตอนแอปสตาร์ตโดย AdminUserInitializer ซึ่งอ่านรหัสจาก environment variable
-- APP_ADMIN_PASSWORD แทน ถ้าไม่ตั้งค่าไว้ ระบบจะไม่สร้างใครเลยและเตือนไว้ใน log
--
-- email กับ phone เป็น null ได้ แอดมินคนแรกที่สร้างจาก environment variable ยังไม่มี
-- ข้อมูลสองช่องนี้ และหน้าจอโปรไฟล์ที่ให้กรอกเพิ่มยังไม่มีในเฟสนี้
CREATE TABLE admin_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(200) NOT NULL,
    email         VARCHAR(255),
    phone         VARCHAR(30),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT admin_user_username_uk UNIQUE (username)
);
