-- ตารางของ epic งานซ่อมบำรุง CR-05 ทั้งก้อน (SSK-18 บันทึกงานซ่อม, SSK-19 ประวัติซ่อม,
-- SSK-20 แจ้งเตือนตามรอบ, SSK-23 คลังอุปกรณ์) อยู่ในไฟล์เดียวเพราะสี่เรื่องนี้อ้างถึงกันเอง
-- ใบแจ้งซ่อมตัดสต็อกอุปกรณ์ และการแจ้งเตือนตามรอบสร้างใบแจ้งซ่อม แยกไฟล์แล้วจะได้
-- ตารางที่ครึ่ง ๆ กลาง ๆ ระหว่างทางซึ่งไม่มีประโยชน์กับใคร
--
-- เลข V8 ถูกจองไว้ให้ไฟล์นี้มาตั้งแต่ V7 แล้ว (ดูหัวคอมเมนต์ของ V7__admin_user.sql
-- และ README หัวข้อ "ที่ยังไม่มี" ข้อ 5)
--
-- ชื่อฟิลด์ฝั่ง API เป็น camelCase ของชื่อคอลัมน์ตรง ๆ ทุกตัว รูปร่างที่ตกลงกับหน้าเว็บ
-- อยู่ใน docs/api-contract-maintenance.md ห้ามแก้ฝ่ายเดียว

-- ใบแจ้งซ่อมหนึ่งใบ (US-12 บันทึกงานซ่อม / US-13 ประวัติรายห้อง)
--
-- ผูกกับห้องเสมอ ไม่มีงานซ่อมที่ไม่สังกัดห้องในระบบนี้ เพราะทั้ง US-12 และ US-13
-- พูดถึงงานซ่อม "ของห้อง" และการ์ดห้องบนแดชบอร์ดอ่านใบที่ยังไม่ปิดของห้องนั้นไปแปะ
-- ถ้าวันหลังมีงานซ่อมส่วนกลาง (ลิฟต์ ดาดฟ้า) ค่อยเปิดให้ room_id เป็น NULL ได้
-- แล้วแก้ที่ RoomService ที่เดียว
CREATE TABLE maintenance_ticket (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT       NOT NULL REFERENCES room (id),
    title            VARCHAR(200) NOT NULL,
    detail           VARCHAR(2000),

    -- ประเภทงานซ่อม (ไฟฟ้า ประปา แอร์ ฯลฯ) เป็นข้อความเปล่า ไม่ใช่ตารางอ้างอิง
    -- เพราะดีไซน์ให้แอดมินพิมพ์เองได้ (frontend/src/domain/maintenanceBoard.ts
    -- ไม่มีรายการค่าตายตัวของช่องนี้) ถ้าวันหลังอยากคุมค่อยทำเป็นตารางแยก
    maintenance_type VARCHAR(50),

    priority         VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    assigned_to      VARCHAR(100),
    reported_by      VARCHAR(100),

    -- วันนัดซ่อม ว่างได้ ดีไซน์ไม่ได้บังคับ (ดูคอมเมนต์ของ date ใน MaintenanceTask ฝั่งหน้าเว็บ)
    scheduled_date   DATE,

    -- ค่าใช้จ่ายเป็น NUMERIC(10,2) ชุดเดียวกับเงินก้อนอื่นทั้งระบบ ว่างได้ เพราะตอนเปิดใบ
    -- ยังไม่รู้ราคา ค่อยมากรอกตอนปิดงาน
    cost             NUMERIC(10, 2),

    status           VARCHAR(15)  NOT NULL DEFAULT 'OPEN',

    -- ใบนี้มาจากไหน MANUAL คือแอดมินกดเปิดเอง RECURRING คือ scheduler สร้างให้จาก
    -- การแจ้งเตือนตามรอบ (US-14) แยกไว้เพื่อให้ตามได้ว่าใบไหนระบบสร้างเอง
    source           VARCHAR(10)  NOT NULL DEFAULT 'MANUAL',

    -- ชี้กลับไปที่ใบแจ้งเตือนที่เป็นต้นทาง ว่างได้ (ใบที่แอดมินเปิดเองไม่มีต้นทาง)
    -- constraint ผูกทีหลังตอนท้ายไฟล์ เพราะตาราง maintenance_reminder เกิดหลังตารางนี้
    reminder_id      BIGINT,

    reported_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- เวลาที่ปิดงาน ตั้งตอนสถานะกลายเป็น DONE และล้างทิ้งถ้ามีการเปิดใบกลับมาใหม่
    closed_at        TIMESTAMPTZ,

    CONSTRAINT maintenance_ticket_priority_ck CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT maintenance_ticket_status_ck   CHECK (status IN ('OPEN', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT maintenance_ticket_source_ck   CHECK (source IN ('MANUAL', 'RECURRING')),
    CONSTRAINT maintenance_ticket_cost_ck     CHECK (cost >= 0)
);

-- คำถามที่ถูกถามบ่อยที่สุดคือ "ห้องนี้มีใบที่ยังไม่ปิดกี่ใบ" ซึ่ง GET /api/rooms
-- ถามทุกครั้งที่โหลดแดชบอร์ด index เดียวกันยังใช้กับประวัติรายห้องของ US-13 ได้ด้วย
CREATE INDEX maintenance_ticket_room_status_ix ON maintenance_ticket (room_id, status);

-- ใบแจ้งเตือนตามรอบหนึ่งใบ สร้างใบแจ้งซ่อมได้ใบเดียวต่อหนึ่งวันครบกำหนด
--
-- ตัวกันใบซ้ำของจริงคือ index ตัวนี้ ไม่ใช่การเช็คในโค้ด เพราะ k8s รัน backend สอง pod
-- (replicas: 2 ใน k8s/20-backend.yaml) งานประจำวันตอนแปดโมงจึงยิงพร้อมกันสองที่ ถ้าไม่มี
-- ตัวกันที่ฐานข้อมูล ทั้งสอง pod จะอ่านเห็นว่าใบถึงกำหนดก่อนที่ฝ่ายไหนจะ commit แล้วสร้าง
-- ใบแจ้งซ่อมคนละใบให้รอบเดียวกัน (ตัวล็อกแถวใน ReminderService.runDue เป็นด่านแรก
-- ที่ทำให้ pod ที่สองไม่ต้องมาชน constraint ตัวนี้ตั้งแต่แรก)
--
-- WHERE reminder_id IS NOT NULL เพราะใบที่แอดมินเปิดเองไม่มีต้นทาง ห้องเดียวกันวันเดียวกัน
-- จะเปิดกี่ใบก็ได้ตามที่ US-12 ต้องการ
CREATE UNIQUE INDEX maintenance_ticket_reminder_due_uk
    ON maintenance_ticket (reminder_id, scheduled_date)
    WHERE reminder_id IS NOT NULL;

-- คลังอุปกรณ์ (US-17) ของที่หยิบไปใช้ในงานซ่อม เช่น หลอดไฟ ก๊อกน้ำ ไส้กรองแอร์
CREATE TABLE supply_item (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,

    -- รหัสของในคลัง ว่างได้เพราะของบางอย่างที่ซื้อจากร้านแถวหอไม่มีรหัสติดมา
    -- แต่ถ้ากรอกมาต้องไม่ซ้ำ ไม่งั้นตอนยิงรหัสเพื่อเบิกของจะได้ของผิดชิ้น
    sku        VARCHAR(50),

    category   VARCHAR(100) NOT NULL,

    -- จำนวนคงเหลือจริงในคลัง ศูนย์ได้ (ของหมด) แต่ติดลบไม่ได้เด็ดขาด
    --
    -- CHECK ตัวนี้เป็นด่านสุดท้ายที่กันไม่ให้ยอดติดลบถูกเขียนลงแถว แต่ **ไม่ใช่** ตัวกัน
    -- การเบิกซ้อนกันของสองคำขอ เพราะ Hibernate เขียนยอดใหม่ทั้งก้อน (SET stock = 3)
    -- ไม่ได้เขียนเป็นส่วนต่าง สองคนที่เบิกจากยอด 5 พร้อมกันจะอ่านได้ 5 ทั้งคู่แล้วเขียนทับกัน
    -- โดยที่ยอดไม่เคยติดลบ ตัวกันเรื่องนั้นคือการล็อกแถวก่อนอ่าน
    -- (SupplyItemRepository.findForUpdateById)
    stock      INTEGER      NOT NULL,

    -- ต่ำกว่าเท่าไหร่ถึงนับว่าใกล้หมด หน้าเว็บคำนวณป้าย Low Stock จาก stock < min_stock
    -- ไม่ได้เก็บสถานะไว้เป็นคอลัมน์ เพราะถ้าเก็บแล้วมีคนแก้จำนวนโดยลืมแก้สถานะ
    -- ตารางจะโชว์ว่าของพอทั้งที่จริงต่ำกว่าขั้นต่ำแล้ว (กฎเดียวกับ supplyStatus
    -- ใน frontend/src/domain/maintenanceBoard.ts)
    min_stock  INTEGER      NOT NULL,

    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT supply_item_sku_uk       UNIQUE (sku),
    CONSTRAINT supply_item_stock_ck     CHECK (stock >= 0),
    CONSTRAINT supply_item_min_stock_ck CHECK (min_stock >= 0)
);

-- ประวัติการเติมของเข้าคลัง (US-17-S2) เก็บเป็นแถวต่อการเติมหนึ่งครั้ง ไม่ได้บวกทับ
-- ลงคอลัมน์ stock อย่างเดียว เพราะการ์ด "restocked this week" ต้องตอบได้ว่าเติมอะไร
-- ไปเท่าไหร่ในช่วงเจ็ดวัน ซึ่งดูจากยอดคงเหลืออย่างเดียวไม่มีทางรู้
CREATE TABLE supply_restock (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supply_id    BIGINT      NOT NULL REFERENCES supply_item (id),
    quantity     INTEGER     NOT NULL,
    restocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- เติมศูนย์หรือติดลบไม่มีความหมาย ถ้าจะลดของให้บันทึกเป็นการใช้ในงานซ่อมแทน
    CONSTRAINT supply_restock_quantity_ck CHECK (quantity > 0)
);

CREATE INDEX supply_restock_restocked_at_ix ON supply_restock (restocked_at);

-- ของที่ใช้ไปกับงานซ่อมใบหนึ่ง (US-12-S1 ตอน "ของที่ใช้ถูกตัดออกจากสต็อกอัตโนมัติ")
-- เก็บแยกเป็นแถวเพื่อให้ย้อนดูได้ว่าใบไหนใช้อะไรไปเท่าไหร่ ไม่ใช่แค่รู้ว่าสต็อกลดลง
CREATE TABLE maintenance_supply_usage (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT      NOT NULL REFERENCES maintenance_ticket (id),
    supply_id BIGINT      NOT NULL REFERENCES supply_item (id),
    quantity  INTEGER     NOT NULL,
    used_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT maintenance_supply_usage_quantity_ck CHECK (quantity > 0)
);

CREATE INDEX maintenance_supply_usage_ticket_ix ON maintenance_supply_usage (ticket_id);

-- การแจ้งเตือนงานซ่อมบำรุงตามรอบ (US-14) เช่น ล้างแอร์ทุกไตรมาส ตรวจดาดฟ้าทุกปี
CREATE TABLE maintenance_reminder (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(200) NOT NULL,
    frequency         VARCHAR(10)  NOT NULL,
    start_date        DATE         NOT NULL,

    -- วันครบกำหนดครั้งถัดไป เก็บไว้เป็นคอลัมน์ ไม่ได้คำนวณสดทุกครั้งจาก start_date
    -- เพราะงานประจำวันที่ scheduler ทำคือ "ใบไหนถึงกำหนดแล้วบ้าง" ซึ่งถ้าคำนวณสด
    -- ต้องดึงทุกแถวมาไล่คิดในโค้ด ส่วนฝั่งหน้าเว็บคำนวณสดได้เพราะถือข้อมูลอยู่ในมือแล้ว
    -- (nextOccurrence ใน frontend/src/domain/maintenanceBoard.ts) สองฝั่งต้องได้ค่าเท่ากัน
    next_due_date     DATE         NOT NULL,

    -- ห้องที่เกี่ยวข้อง ว่างได้ เพราะงานอย่างตรวจดาดฟ้าหรือล้างถังน้ำเป็นงานของทั้งตึก
    -- ช่องนี้คือช่อง unit ในดีไซน์ ซึ่งฝั่งหน้าเว็บเก็บเป็นเลขห้องเปล่า ๆ ส่วนที่นี่ผูกเป็น
    -- foreign key จริง เลขห้องที่ไม่มีอยู่จะเข้ามาไม่ได้ตั้งแต่แรก
    room_id           BIGINT       REFERENCES room (id),

    -- เวลาที่อยากให้เตือน ว่างได้ ตอนนี้ scheduler ยังยิงรอบเดียวตอน 8 โมงเช้า
    -- ช่องนี้จึงเป็นข้อมูลให้คนอ่าน ไม่ได้เปลี่ยนเวลาที่ระบบสร้างใบแจ้งซ่อมจริง
    remind_time       TIME,

    priority          VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    notes             VARCHAR(2000),

    -- ปิดสวิตช์ไว้ก่อนได้โดยไม่ต้องลบทิ้ง ใบรอบเดียว (ONE_TIME) ที่ยิงไปแล้วก็ถูกปิดที่นี่
    active            BOOLEAN      NOT NULL DEFAULT true,

    -- ครั้งล่าสุดที่ระบบสร้างใบแจ้งซ่อมจากใบนี้ ว่างได้ (ยังไม่เคยถึงกำหนด)
    last_triggered_at TIMESTAMPTZ,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT maintenance_reminder_frequency_ck CHECK (frequency IN ('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'ANNUAL')),
    CONSTRAINT maintenance_reminder_priority_ck  CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT'))
);

-- ผูก foreign key ของ reminder_id ตรงนี้ ไม่ได้ผูกตอน CREATE TABLE ข้างบน เพราะตาราง
-- ปลายทางเพิ่งเกิดในไฟล์เดียวกันนี้เอง ถ้าสลับลำดับตารางแทนก็ได้ แต่การอ่านไฟล์จะเริ่ม
-- จากตารางรองแทนที่จะเป็นตารางหลักของ epic นี้
ALTER TABLE maintenance_ticket
    ADD CONSTRAINT maintenance_ticket_reminder_fk
        FOREIGN KEY (reminder_id) REFERENCES maintenance_reminder (id);
