-- ใบเสร็จค่าเช่าของ US-10 (SSK-16) หนึ่งแถวคือใบเสร็จหนึ่งใบของสัญญาหนึ่งใบในหนึ่งเดือน
--
-- เลข V9 ต่อจาก V8__maintenance.sql (ใบแจ้งซ่อมของ CR-05) ซึ่งอยู่ใน PR ก่อนหน้าของสายเดียวกัน
-- ลำดับ merge จึงเป็น V8 แล้วค่อย V9 เสมอ ไม่ต้องเปิด out-of-order ของ Flyway

CREATE TABLE receipt (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- รูปแบบ RC-<ปี ค.ศ.>-<ลำดับ 4 หลักของปีนั้น> เช่น RC-2026-0001 ยาวสุด 12 ตัวอักษร
    -- เผื่อไว้ 20 ให้ขึ้นเป็น 5 หลักได้โดยไม่ต้อง migrate คอลัมน์ ถ้าวันหนึ่งหอโตกว่านี้
    --
    -- ตัวกันเลขซ้ำของจริงอยู่ที่ receipt_no_uk ตรงนี้ที่เดียว การนับใบของปีนั้นแล้ว +1
    -- ใน ReceiptService กันสองคำขอที่เข้ามาพร้อมกันไม่ได้ ทั้งคู่จะนับได้เลขเดียวกัน
    -- แล้วมาโดน constraint นี้ตอนเขียน ฝั่งโค้ดจึงต้องลองใหม่เมื่อชนกับ constraint นี้
    receipt_no VARCHAR(20) NOT NULL,

    lease_id   BIGINT      NOT NULL REFERENCES lease (id),

    -- เก็บเป็นวันที่ 1 ของเดือนที่เรียกเก็บเสมอ ไม่ได้เก็บเป็น VARCHAR 'YYYY-MM'
    -- เพราะต้องเอาไปเรียงและเทียบช่วงเดือน ซึ่ง DATE ทำได้ตรง ๆ ส่วน API รับส่งเป็น
    -- 'YYYY-MM' ตามที่ตกลงกับหน้าเว็บ การแปลงสองทางอยู่ใน ReceiptService ที่เดียว
    billing_month DATE     NOT NULL,

    -- หน่วยที่จดจากมิเตอร์ในรอบนั้น เก็บทศนิยมสองตำแหน่งเพราะมิเตอร์น้ำบางรุ่นอ่านเป็นจุด
    electric_units NUMERIC(10, 2) NOT NULL,
    water_units    NUMERIC(10, 2) NOT NULL,

    -- ห้าคอลัมน์นี้คือ snapshot ของอัตราที่ใช้คิดใบนี้จริง ๆ มีอยู่เพราะ US-16-S3
    --
    -- ใบเสร็จคัดลอกอัตรามาจาก "สัญญา" (lease) ซึ่งเองก็คัดลอกมาจาก apartment_config
    -- ตั้งแต่วันเซ็นอีกที ใบเสร็จจึงไม่เคยอ่าน apartment_config เลยแม้แต่ตอนออกใบใหม่
    -- ถ้าอ่าน วันที่แอดมินขึ้นค่าไฟ ใบเสร็จเก่าทุกใบจะเปลี่ยนยอดย้อนหลังตามไปด้วย
    -- ซึ่งผิดทั้งทางบัญชีและทางกฎหมาย เพราะผู้เช่าจ่ายตามยอดที่พิมพ์ไปแล้ว
    --
    -- เหตุผลเดียวกับคอลัมน์ชุด rate ในตาราง lease (V4) แต่ต้องเก็บซ้ำอีกชั้นที่นี่
    -- เพราะสัญญาใบเดียวถูกแก้อัตราได้ทีหลัง (PUT /api/leases/{id}) ใบเสร็จที่ออกไปแล้ว
    -- ต้องไม่ขยับตาม และ monthly_rent ก็ต้องเก็บด้วยเพราะค่าเช่าแก้ได้เหมือนกัน
    monthly_rent           NUMERIC(10, 2) NOT NULL,
    electric_rate_per_unit NUMERIC(10, 2) NOT NULL,
    water_rate_per_unit    NUMERIC(10, 2) NOT NULL,
    common_area_fee        NUMERIC(10, 2) NOT NULL,
    internet_fee           NUMERIC(10, 2) NOT NULL,

    -- ยอดที่คิดแล้ว เก็บไว้ไม่ได้คำนวณสดตอนอ่าน เพราะใบเสร็จที่พิมพ์ส่งผู้เช่าไปแล้ว
    -- ต้องอ่านได้ยอดเดิมเสมอ ถึงสูตรคิดเงินจะถูกแก้ทีหลังก็ตาม
    electric_amount NUMERIC(10, 2) NOT NULL,
    water_amount    NUMERIC(10, 2) NOT NULL,
    total_amount    NUMERIC(10, 2) NOT NULL,

    issued_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_date   DATE        NOT NULL,

    status     VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    paid_at    TIMESTAMPTZ,
    payment_method VARCHAR(50),

    CONSTRAINT receipt_no_uk UNIQUE (receipt_no),

    -- สัญญาใบเดียวมีใบเสร็จของเดือนเดียวกันได้ใบเดียว ตัวกันออกใบซ้ำของจริงอยู่ตรงนี้
    -- การเช็คใน ReceiptService เป็นแค่การทำให้ข้อความที่ผู้ใช้เห็นอ่านรู้เรื่อง
    -- กฎเดียวกับ lease_no_overlap ใน V4 และ tenant_national_id_uk ใน V6
    CONSTRAINT receipt_lease_month_uk UNIQUE (lease_id, billing_month),

    -- ต้องเป็นวันที่ 1 ของเดือนเสมอ ไม่งั้นใบเสร็จของเดือนเดียวกันที่บันทึกคนละวัน
    -- จะเล็ดลอด receipt_lease_month_uk ไปได้ กลายเป็นออกใบซ้ำเดือนโดยไม่มีอะไรกัน
    CONSTRAINT receipt_month_first_day_ck CHECK (EXTRACT(DAY FROM billing_month) = 1),

    CONSTRAINT receipt_units_ck CHECK (electric_units >= 0 AND water_units >= 0),

    CONSTRAINT receipt_rates_ck CHECK (monthly_rent >= 0
                                   AND electric_rate_per_unit >= 0
                                   AND water_rate_per_unit >= 0
                                   AND common_area_fee >= 0
                                   AND internet_fee >= 0),

    CONSTRAINT receipt_amounts_ck CHECK (electric_amount >= 0
                                     AND water_amount >= 0
                                     AND total_amount >= 0),

    CONSTRAINT receipt_status_ck CHECK (status IN ('PENDING', 'PAID')),

    -- จ่ายแล้วต้องมีวันที่จ่าย และยังไม่จ่ายต้องไม่มี ผูกสองคอลัมน์ไว้ด้วยกันตั้งแต่ระดับ
    -- ตาราง ไม่งั้นจะมีแถวที่ status เป็น PAID แต่ paid_at ว่าง ซึ่งหน้าเว็บโชว์ไม่ได้
    CONSTRAINT receipt_paid_ck CHECK ((status = 'PAID') = (paid_at IS NOT NULL))
);

-- หน้า Payments กรองด้วยสัญญาและเรียงใบใหม่สุดขึ้นก่อนทุกครั้งที่โหลด
CREATE INDEX receipt_lease_ix ON receipt (lease_id);
CREATE INDEX receipt_issued_at_ix ON receipt (issued_at DESC);
